### ISSUE TITLE
Problem when asking more precision than default currency precision

### ISSUE THREAD

**Issue by verhaeghep** [lillik/magento2-price-decimal#3]
Thank you for your Magento 2 extension.
When I activate your extension and use for example "4" as decimal length, I have 2 issues:
- Admin backend still uses 2 as decimal length (as default when using Euro as currency). So nothing has changed at the backend.
- Frontend shows 4 decimals but round every price to 2 decimals (e.g. price 36.9050 in the database becomes 36.9100 on the frontend).

Can you help me? Did I configure something wrong? Or is this a bug in the extension? Thanks in advance.

**Comment by mzenner1** [comment]
I'm also looking to use 4 decimal places on my site, but it's not taking.  Any word on if this module has the ability to go above 2 places?

**Comment by ctadlock** [comment]
@lillik  The ability to increase the precision to 3 or 4 would be of huge value.

**Comment by magulin** [comment]
One of the problems seems to be the round($price) function in Magento\Directory\Model\PriceCurrency which is hardcoded to 2 decimals. Without overriding this it is impossible to complete the checkout process with 4 decimals, as the quote items will be saved as 1,2300 instead of 1,2345 in the database.

**Comment by lillik** [comment]
Please take a look, backend bug was fixed.

**Comment by mzenner1** [comment]
Magento 2.1.9

This bug is not quite fixed yet.  The 4 decimal places render on the backend correctly now, but round down to 2 decimal places on the front end product detail page and the cart.

Backend: $215.1234
Frontend: $215.1200

**Comment by eyesoverrun** [comment]
I have the same problem with Magento 2.1.8

**Comment by rab14191** [comment]
how to activate this module ? where is  option in backeend ? enable or disable

**Comment by lillik** [comment]
@rab14191 
Stores->Configuration->Catalog

**Comment by rab14191** [comment]
yes i got it..but  still in cart in price display  decimal number which i want to remove as well
in admin   in order everywhere  decimal number is showing which i want to remove

**Comment by lillik** [comment]
I'm gonna go to close this issue. 
I created new issue related to second part of current issues. [frontend round](https://github.com/lillik/magento2-price-decimal/issues/19)
@rab14191  please open new issue with your problem, it will be fixed.
